'use client'
import { useEffect, useState, useCallback } from 'react'
import AuthGate from '@/components/AuthGate'
import { api, ToolRequestItem } from '@/lib/api'

type FilterStatus = 'all' | 'needs_review' | 'done' | 'killed' | 'queued'

const STATUS_STYLES: Record<string, string> = {
  queued: 'bg-slate-600 text-slate-200',
  running: 'bg-blue-700 text-blue-100',
  blocked: 'bg-red-700 text-red-100',
  needs_review: 'bg-yellow-700 text-yellow-100',
  done: 'bg-green-700 text-green-100',
  killed: 'bg-slate-700 text-slate-400 line-through',
}

const STATUS_LABELS: Record<string, string> = {
  queued: '대기',
  running: '진행중',
  blocked: '차단됨',
  needs_review: '검토필요',
  done: '완료',
  killed: '종료',
}

const PRIORITY_STYLES: Record<string, string> = {
  high: 'bg-red-800 text-red-200',
  medium: 'bg-yellow-800 text-yellow-200',
  low: 'bg-slate-600 text-slate-300',
}

function relativeTime(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 1) return '방금'
  if (mins < 60) return `${mins}분 전`
  const hours = Math.floor(mins / 60)
  if (hours < 24) return `${hours}시간 전`
  return `${Math.floor(hours / 24)}일 전`
}

// Extract occurrence count from rationale generated by generateToolRequestTask()
function parseOccurrences(rationale: string): number | null {
  const m = rationale.match(/repeated (\d+) times/)
  return m ? parseInt(m[1]!, 10) : null
}

// Extract agents from rationale: "across agents: CMO, CTO"
function parseAgents(rationale: string): string[] {
  const m = rationale.match(/across agents?: ([^\\.]+)/)
  if (!m) return []
  return m[1]!.split(',').map(s => s.trim()).filter(Boolean)
}

// Extract pattern name from title: "Tool Request: <pattern>"
function parsePatternName(title: string): string {
  return title.startsWith('Tool Request: ') ? title.slice('Tool Request: '.length) : title
}

// Derive automation priority from occurrence count (mirrors l5-core logic)
function derivePriority(occurrences: number | null): 'high' | 'medium' | 'low' {
  if (occurrences === null) return 'low'
  if (occurrences >= 10) return 'high'
  if (occurrences >= 5) return 'medium'
  return 'low'
}

const TABS: { key: FilterStatus; label: string }[] = [
  { key: 'all', label: '전체' },
  { key: 'needs_review', label: '검토필요' },
  { key: 'queued', label: '대기' },
  { key: 'done', label: '완료' },
  { key: 'killed', label: '종료' },
]

function ToolRequestsContent() {
  const [items, setItems] = useState<ToolRequestItem[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState<FilterStatus>('all')
  const [autoRefresh, setAutoRefresh] = useState(true)

  const load = useCallback(async () => {
    try {
      const data = await api.listToolRequests()
      setItems(data)
    } catch {
      setItems([])
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    load()
    if (!autoRefresh) return
    const interval = setInterval(load, 30000)
    return () => clearInterval(interval)
  }, [load, autoRefresh])

  const filtered = items.filter(item => {
    if (filter === 'all') return true
    return item.status === filter
  })

  const counts = TABS.reduce<Record<string, number>>((acc, tab) => {
    acc[tab.key] = tab.key === 'all'
      ? items.length
      : items.filter(i => i.status === tab.key).length
    return acc
  }, {})

  return (
    <div>
      <div className="flex items-center gap-4 mb-4">
        <h1 className="text-xl font-bold">Tool Requests</h1>
        <span className="text-xs text-slate-400">반복 작업 자동화 요청 추적</span>
        <label className="ml-auto flex items-center gap-2 text-xs text-slate-400 cursor-pointer">
          <input
            type="checkbox"
            checked={autoRefresh}
            onChange={e => setAutoRefresh(e.target.checked)}
            className="rounded"
          />
          30초 자동 새로고침
        </label>
        <button onClick={load} className="text-xs text-slate-400 hover:text-slate-200">새로고침</button>
      </div>

      {/* Filter tabs */}
      <div className="flex gap-1 mb-6 border-b border-slate-700">
        {TABS.map(tab => (
          <button
            key={tab.key}
            onClick={() => setFilter(tab.key)}
            className={`px-4 py-2 text-sm transition-colors border-b-2 -mb-px ${
              filter === tab.key
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            {tab.label}
            {counts[tab.key] > 0 && (
              <span className="ml-1.5 text-xs bg-slate-700 text-slate-300 rounded-full px-1.5">
                {counts[tab.key]}
              </span>
            )}
          </button>
        ))}
      </div>

      {loading && <div className="text-slate-400">로딩 중...</div>}

      {!loading && filtered.length === 0 && (
        <div className="text-center text-slate-500 mt-12 text-sm">
          {filter === 'all'
            ? 'Tool Request가 없습니다. Hermes 반복 분석기가 2시간마다 실행됩니다.'
            : '해당 상태의 항목이 없습니다.'}
        </div>
      )}

      <div className="grid gap-3">
        {filtered.map(item => {
          const patternName = parsePatternName(item.task_title)
          const occurrences = parseOccurrences(item.rationale)
          const agents = parseAgents(item.rationale)
          const priority = derivePriority(occurrences)

          return (
            <div key={item.task_id} className="bg-slate-800 rounded-xl p-4">
              {/* Header row */}
              <div className="flex flex-wrap items-center gap-2 mb-2">
                <span className="text-xs font-medium bg-cyan-900 text-cyan-300 rounded px-2 py-0.5">CTO</span>
                <span className={`text-xs rounded px-2 py-0.5 ${STATUS_STYLES[item.status] ?? 'bg-slate-600'}`}>
                  {STATUS_LABELS[item.status] ?? item.status}
                </span>
                <span className={`text-xs rounded px-2 py-0.5 ${PRIORITY_STYLES[priority]}`}>
                  {priority === 'high' ? '높음' : priority === 'medium' ? '보통' : '낮음'} 우선순위
                </span>
                {item.risk_level && (
                  <span className="text-xs bg-blue-800 text-blue-200 rounded px-2 py-0.5">{item.risk_level}</span>
                )}
                {item.approval_required && (
                  <span className="text-xs bg-yellow-900 text-yellow-300 rounded px-2 py-0.5">승인필요</span>
                )}
              </div>

              {/* Pattern name */}
              <div className="font-medium text-sm mb-2">{patternName}</div>

              {/* Pattern summary */}
              <div className="flex flex-wrap gap-4 text-xs text-slate-400 mb-2">
                {occurrences !== null && (
                  <span>반복 횟수: <span className="text-slate-200 font-medium">{occurrences}회</span></span>
                )}
                {agents.length > 0 && (
                  <span>관련 에이전트: <span className="text-slate-200">{agents.join(', ')}</span></span>
                )}
                {item.phase && (
                  <span>Phase: <span className="text-slate-300">{item.phase}</span></span>
                )}
              </div>

              {/* Rationale (CTO feasibility detail) */}
              <div className="text-xs text-slate-400 line-clamp-3 mb-2">{item.rationale}</div>

              {/* Blocker */}
              {item.blocker && (
                <div className="text-xs text-red-400 mt-1">차단: {item.blocker}</div>
              )}

              {/* Timestamp */}
              <div className="text-xs text-slate-600 mt-2">{relativeTime(item.updated_at)}</div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

export default function ToolRequestsPage() {
  return <AuthGate><ToolRequestsContent /></AuthGate>
}
